### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by BorisKourt** [jparyani/lets-chat#1]
Is there a way to modify the configuration of this app when its installed on sandstorm? 

Hopefully in a way that persists with updates?

Thanks.

**Comment by jparyani** [comment]
Unfortunately, configuration that is locked behind settings.yml/environment variables are not able to be configured.

The hope is one day that these settings move to a settings page within the app.

**Comment by BorisKourt** [comment]
I will keep an eye out for this.
Thanks.
