### ISSUE TITLE
XMPP Access

### ISSUE THREAD

**Issue by BorisKourt** [jparyani/lets-chat#2]
As the URL scheme is very different when this is running in a sandstorm app, is there a way to get access via XMPP? 

If not, are there modifications that I can do to make it happen? 

And as a broader question, the main reason for this is to run the app on sandstorm, but use desktop + mobile clients. As the chat experience is sub-optimal when its hidden & forgotten in a browser tab somewhere.

Have you had any luck with that yourself? 

Thank you for putting this together!

**Comment by BorisKourt** [comment]
An alternative to XMPP would work too, I am just not sure what else Let's Chat supports out of the box.

**Comment by jparyani** [comment]
Sandstorm does not allow for arbitrary protocols such as XMPP to be exported by apps, yet. Work is ongoing to add "drivers" that will allow apps to export such interfaces (see https://github.com/sandstorm-io/sandstorm/wiki/Sandstorm-App-Developer-Handbook#is-isolated, 3rd paragraph for a discussion on this).

**Comment by BorisKourt** [comment]
Thank you for clarifying. Closing.
