### ISSUE TITLE
Request to update

### ISSUE THREAD

**Issue by ndarilek** [jparyani/lets-chat#3]
Not sure what the protocol on this is. I just merged some accessibility fixes into upstream master that make LC easier to use with screen readers. It'd be great if the Sandstorm app can be upgraded to take advantage of those. I'd like to deploy it sometime this weekend and am a screen reader user myself, so having an accessible lets-chat would be great.

Thanks!

**Comment by jparyani** [comment]
Alright, can you give `/install/7d7f3125bb036543f272610e7c50381a?url=http://sandstorm.io/apps/jparyani/letschat-5.spk` a try (either append that to your host name ie. https://alpha.sandstorm.io/install/7d7f3125bb036543f272610e7c50381a?url=http://sandstorm.io/apps/jparyani/letschat-5.spk or just download http://sandstorm.io/apps/jparyani/letschat-5.spk).

If it works for you, I'll update the version on the app list as well.

**Comment by ndarilek** [comment]
Just tried this in my Sandstorm instance and it works great. Thanks!

I may periodically add additional access fixes to LC. If I do then I'll
ping with another issue.

**Comment by jparyani** [comment]
Alright, the new version should be up on the app list.

Feel free to ping me whenever you want an update.
