### ISSUE TITLE
App Graphics for Sandstorm

### ISSUE THREAD

**Issue by neynah** [jparyani/lets-chat#5]
@jparyani 

Thoughts on these? If they're good to go, I'll submit a pull request to this repo.

![letschat-preview1](https://cloud.githubusercontent.com/assets/855341/9265908/d8bec504-41ee-11e5-9b0d-150d1becdc42.png)

**Comment by jparyani** [comment]
It makes me a little sad that the icon in the sidebar doesn't match the bigger icon (are we calling them banners?).

Otherwise, LGTM

**Comment by neynah** [comment]
@jparyani 

Please don't be sad! :)

(Also I think Kenton/Drew have been referring to the App Market graphic as banners, the others are icons)
![letschat-preview2](https://cloud.githubusercontent.com/assets/855341/9282674/f2856dd2-4282-11e5-9d44-56272b3753f0.png)

**Comment by jparyani** [comment]
LGTM

**Comment by jparyani** [comment]
This was resolved in #6
